[package]
name = "toolbox"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"
opt-level = "z"

[dependencies]
eframe = "0.31.0"
winapi = { version = "0.3.9", features = ["winuser", "shellapi"] }

[build-dependencies]
winres = "0.1"
