macro_rules! define_tools {
    ($($cate:expr => [$(($name:expr, $path:expr)),* $(,)?]),* $(,)?) => {
        &[$($(
            Tool { name: $name, path: $path, category: $cate, },
        )*)*]
    };
}

pub static CATEGORIES: &[&str] = &[
    "CPU工具",
    "主板工具",
    "内存工具",
    "显卡工具",
    "磁盘工具",
    "屏幕工具",
    "综合工具",
    "外设工具",
    "烤机工具",
    "其他工具",
];

pub struct Tool<'a> {
    pub name: &'a str,
    pub path: &'a str,
    pub category: &'a str,
}

pub static TOOLS: &[Tool<'static>] = define_tools!(
    "CPU工具" => [
        ("CPU-Z (64位)", ".\\tools\\处理器工具\\CPUZ\\cpuz_x64.exe"),
        ("CPU-Z (32位)", ".\\tools\\处理器工具\\CPUZ\\cpuz_x32.exe"),
        ("LinX", ".\\tools\\处理器工具\\LinX\\LinX.exe"),
        ("Prime95", ".\\tools\\处理器工具\\Prime95\\prime95.exe"),
        ("Superpi", ".\\tools\\处理器工具\\superpi\\Superpi.exe"),
        ("wPrime", ".\\tools\\处理器工具\\wPrime\\wPrime.exe"),
        ("FritzChess Benchmark", ".\\tools\\处理器工具\\XIANGQI\\xiangqi.exe"),
        ("Core Temp (64位)", ".\\tools\\处理器工具\\CoreTemp\\Core Temp x64.exe"),
        ("Core Temp (32位)", ".\\tools\\处理器工具\\CoreTemp\\Core Temp x86.exe"),
        ("cpuburner", ".\\tools\\烤鸡工具\\FurMark\\cpuburner.exe"),
        ("ThrottleStop", ".\\tools\\处理器工具\\ThrottleStop\\ThrottleStop.exe"),
    ],
    "主板工具" => [
        ("AIDA64", ".\\tools\\综合检测\\AIDA64\\aida64.exe"),
    ],
    "内存工具" => [
        ("MemTest", ".\\tools\\内存工具\\memtest\\memtest.exe"),
        ("MemTest64", ".\\tools\\内存工具\\memtest64\\MemTest64.exe"),
        ("魔方内存盘", ".\\tools\\内存工具\\魔方内存盘\\ramdisk.exe"),
        ("Thaiphoon", ".\\tools\\内存工具\\Thaiphoon\\Thaiphoon.exe"),
        ("MemTest pro", ".\\tools\\内存工具\\memtestpro\\memtestpro.exe"),
        ("TM5", ".\\tools\\内存工具\\tm5\\TM5.exe"),
    ],
    "显卡工具" => [
        ("GPU-Z", ".\\tools\\显卡工具\\GPUZ\\GPU-Z.exe"),
        ("FurMark", ".\\tools\\烤鸡工具\\FurMark\\FurMark.exe"),
        ("FurMark2", ".\\tools\\烤鸡工具\\FurMark_win64\\FurMark_GUI.exe"),
        ("GpuTest", ".\\tools\\显卡工具\\GpuTest_Windows x64\\GpuTest_GUI.exe"),
        ("DXVAChecker", ".\\tools\\显卡工具\\dxvachecker\\DXVAChecker.exe"),
        ("nvidiaInspector", ".\\tools\\显卡工具\\nvidiaInspector\\nvidiaInspector.exe"),
        ("nvidiaProfileInspector", ".\\tools\\显卡工具\\nvidiaProfileInspector\\nvidiaProfileInspector.exe"),
        ("Display Driver Uninstaller", ".\\tools\\显卡工具\\DDU\\Display Driver Uninstaller.exe"),
        ("gpushark2.0", ".\\tools\\烤鸡工具\\FurMark_win64\\gpushark\\gpushark_x64.exe"),
    ],
    "磁盘工具" => [
        ("ASSSDBenchmark", ".\\tools\\硬盘工具\\ASSSDBenchmark\\ASSSDBenchmark.exe"),
        ("DiskInfo（64位）", ".\\tools\\硬盘工具\\CrystalDiskInfo\\DiskInfo64S.exe"),
        ("DiskInfo（32位）", ".\\tools\\硬盘工具\\CrystalDiskInfo\\DiskInfo32S.exe"),
        ("DiskMark（64位）", ".\\tools\\硬盘工具\\CrystalDiskMark\\DiskMark64.exe"),
        ("DiskMark（32位）", ".\\tools\\硬盘工具\\CrystalDiskMark\\DiskMark32.exe"),
        ("HDTune", ".\\tools\\硬盘工具\\HDTune\\HDTune.exe"),
        ("ATTO 磁盘基准测试", ".\\tools\\硬盘工具\\ATTODISKBENCHMARK\\ATTO 磁盘基准测试.exe"),
        ("Defraggler", ".\\tools\\硬盘工具\\Defraggler\\Defraggler.exe"),
        ("DiskGenius", ".\\tools\\硬盘工具\\DiskGenius\\DiskGenius.exe"),
        ("MyDiskTest", ".\\tools\\硬盘工具\\mydisktest\\MyDiskTest_v298.exe"),
        ("魔方数据恢复", ".\\tools\\硬盘工具\\魔方数据恢复\\魔方数据恢复.exe"),
        ("FINALDATA", ".\\tools\\硬盘工具\\finaldata\\FINALDATA.exe"),
        ("FdWizard", ".\\tools\\硬盘工具\\finaldata\\FdWizard.exe"),
        ("LLFTOOL", ".\\tools\\硬盘工具\\LLFTOOL\\LLFTOOL.exe"),
        ("h2testw_1.4", ".\\tools\\硬盘工具\\H2testw\\h2testw_1.4.exe"),
        ("urwtest_v18", ".\\tools\\硬盘工具\\URWTEST\\urwtest_v18.exe"),
        ("windirstat", ".\\tools\\硬盘工具\\windirstat\\windirstat.exe"),
        ("SpaceSniffer", ".\\tools\\硬盘工具\\SpaceSniffer\\SpaceSniffer.exe"),
        ("SSDZ", ".\\tools\\硬盘工具\\SSDZ\\SSDZ.exe"),
    ],
    "屏幕工具" => [
        ("坏点与漏光测试", ".\\tools\\显示器工具\\在线屏幕测试\\在线屏幕测试.bat"),
        ("显示器色域检测", ".\\tools\\显示器工具\\色域检测\\monitorinfo.exe"),
        ("UFO测试", ".\\tools\\显示器工具\\UFO测试\\Start.bat"),
    ],
    "综合工具" => [
        ("AIDA64", ".\\tools\\综合检测\\AIDA64\\aida64.exe"),
        ("HWiNFO（64位）", ".\\tools\\综合检测\\hwinfo\\HWiNFO64.exe"),
        ("HWiNFO（32位）", ".\\tools\\综合检测\\hwinfo\\HWiNFO32.exe"),
        ("Speccy（64位）", ".\\tools\\综合检测\\speccy\\Speccy64.exe"),
        ("Speccy（32位）", ".\\tools\\综合检测\\speccy\\Speccy32.exe"),
        ("RWEverything", ".\\tools\\综合检测\\RWEverything\\Rw.exe"),
        ("HWMonitor（64位）", ".\\tools\\综合检测\\HWMonitor\\HWMonitor_x64.exe"),
        ("HWMonitor（32位）", ".\\tools\\综合检测\\HWMonitor\\HWMonitor_x32.exe"),
    ],
    "外设工具" => [
        ("Keyboard Test Utility", ".\\tools\\外设工具\\Keyboard Test Utility\\Keyboard Test Utility.exe"),
        ("鼠标单机变双击测试器", ".\\tools\\外设工具\\鼠标单机变双击测试器\\鼠标单击变双击测试器V2.0.exe"),
        ("MOUSERATE", ".\\tools\\外设工具\\MOUSERATE\\MOUSERATE.exe"),
        ("AresonMouseTest", ".\\tools\\外设工具\\AresonMouseTest\\鼠标测试软件AresonMouseTestProgram.exe"),
        ("KeyTweak", ".\\tools\\外设工具\\KeyTweak\\KeyTweak.exe"),
        ("MouseTester", ".\\tools\\外设工具\\MouseTester\\MouseTester.exe"),
    ],
    "烤机工具" => [
        ("FurMark", ".\\tools\\烤鸡工具\\FurMark\\FurMark.exe"),
        ("GpuTest", ".\\tools\\显卡工具\\GpuTest_Windows x64\\GpuTest_GUI.exe"),
        ("Prime95", ".\\tools\\处理器工具\\Prime95\\prime95.exe"),
        ("LinX", ".\\tools\\处理器工具\\LinX\\LinX.exe"),
        ("AIDA64", ".\\tools\\综合检测\\AIDA64\\aida64.exe"),
        ("cpuburner", ".\\tools\\烤鸡工具\\FurMark\\cpuburner.exe"),
        ("FurMark2", ".\\tools\\烤鸡工具\\FurMark_win64\\FurMark_GUI.exe"),
    ],
    "其他工具" => [
        ("BatteryInfoView", ".\\tools\\其他工具\\BatteryInfoView\\BatteryInfoView.exe"),
        ("ULTRAISO", ".\\tools\\其他工具\\UltraISO\\UltrULTRAISOaISO.exe"),
        ("Geek Uninstaller", ".\\tools\\其他工具\\Geek Uninstaller\\Geek Uninstaller.exe"),
        ("Dism++x64", ".\\tools\\其他工具\\Dism++\\Dism++x64.exe"),
        ("Dism++x86", ".\\tools\\其他工具\\Dism++\\Dism++x86.exe"),
        ("Dism++ARM64", ".\\tools\\其他工具\\Dism++\\Dism++ARM64.exe"),
        ("BlueScreenView（64位）", ".\\tools\\其他工具\\bluescreenview\\BlueScreenViewx64.exe"),
        ("BlueScreenView（32位）", ".\\tools\\其他工具\\bluescreenview\\BlueScreenViewx86.exe"),
        ("windbg", ".\\tools\\其他工具\\WinDbg\\windbg.exe"),
        ("procexp（64位）", ".\\tools\\其他工具\\procexp\\procexp64.exe"),
        ("procexp（32位）", ".\\tools\\其他工具\\procexp\\procexp32.exe"),
        ("rufus", ".\\tools\\其他工具\\rufus\\rufus.exe"),
        ("Ventoy2Disk", ".\\tools\\其他工具\\ventoy\\Ventoy2Disk.exe"),
        ("Everything", ".\\tools\\其他工具\\Everything\\everything.exe"),
        ("GifCam", ".\\tools\\其他工具\\gifcam\\GifCam.exe"),
        ("DesktopOK", ".\\tools\\其他工具\\DesktopOK\\DesktopOK.exe"),
        ("DirectX Repair", ".\\tools\\其他工具\\DirectX_Repair\\DirectX Repair.exe"),
        ("NEXT ITELL YOU", ".\\tools\\其他工具\\next_itellyou\\Start.bat"),
        ("WTG辅助工具", ".\\tools\\其他工具\\WTGA\\wintogo.exe"),
    ],
);
