name: CI Workflow

permissions:
  contents: write

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build project
        run: |
          cargo build --release
          mv target/release/toolbox.exe 图吧工具箱.exe

      - name: Get current date
        id: date
        run: echo "date=$(Get-Date -Format 'yyyy-MM-dd')" >> $env:GITHUB_OUTPUT

      - name: Release artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          files: 图吧工具箱.exe
